// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ingredientsFieldNames          = builder.RawFieldNames(&Ingredients{})
	ingredientsRows                = strings.Join(ingredientsFieldNames, ",")
	ingredientsRowsExpectAutoSet   = strings.Join(stringx.Remove(ingredientsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ingredientsRowsWithPlaceHolder = strings.Join(stringx.Remove(ingredientsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	ingredientsModel interface {
		Insert(ctx context.Context, data *Ingredients) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Ingredients, error)
		FindOneByIngredientName(ctx context.Context, ingredientName string) (*Ingredients, error)
		Update(ctx context.Context, data *Ingredients) error
		SelectBuilder() squirrel.SelectBuilder
		FindAll(context.Context, squirrel.SelectBuilder, string) ([]*Ingredients, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Ingredients, error)

		Delete(ctx context.Context, id int64) error
	}

	defaultIngredientsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Ingredients struct {
		Id                     int64  `db:"id"`                       // 食材ID
		IngredientName         string `db:"ingredient_name"`          // 食材名称
		IngredientImageContent string `db:"ingredient_image_content"` // 食材图片地址
		IngredientDescription  string `db:"ingredient_description"`   // 食材描述
	}
)

func newIngredientsModel(conn sqlx.SqlConn) *defaultIngredientsModel {
	return &defaultIngredientsModel{
		conn:  conn,
		table: "`ingredients`",
	}
}

func (m *defaultIngredientsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultIngredientsModel) FindOne(ctx context.Context, id int64) (*Ingredients, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ingredientsRows, m.table)
	var resp Ingredients
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultIngredientsModel) FindOneByIngredientName(ctx context.Context, ingredientName string) (*Ingredients, error) {
	var resp Ingredients
	query := fmt.Sprintf("select %s from %s where `ingredient_name` = ? limit 1", ingredientsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, ingredientName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultIngredientsModel) Insert(ctx context.Context, data *Ingredients) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, ingredientsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.IngredientName, data.IngredientImageContent, data.IngredientDescription)
	return ret, err
}

func (m *defaultIngredientsModel) Update(ctx context.Context, newData *Ingredients) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ingredientsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.IngredientName, newData.IngredientImageContent, newData.IngredientDescription, newData.Id)
	return err
}

func (m *defaultIngredientsModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}

func (m *defaultIngredientsModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*Ingredients, error) {

	builder = builder.Columns(ingredientsRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	// query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	query, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Ingredients

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultIngredientsModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Ingredients, error) {

	builder = builder.Columns(ingredientsRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	// query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	query, values, err := builder.OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Ingredients

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultIngredientsModel) tableName() string {
	return m.table
}
