// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	recipeIngredientsFieldNames          = builder.RawFieldNames(&RecipeIngredients{})
	recipeIngredientsRows                = strings.Join(recipeIngredientsFieldNames, ",")
	recipeIngredientsRowsExpectAutoSet   = strings.Join(stringx.Remove(recipeIngredientsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	recipeIngredientsRowsWithPlaceHolder = strings.Join(stringx.Remove(recipeIngredientsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	recipeIngredientsModel interface {
		Insert(ctx context.Context, data *RecipeIngredients) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RecipeIngredients, error)
		FindOneByIdIngredientId(ctx context.Context, id int64, ingredientId sql.NullInt64) (*RecipeIngredients, error)
		Update(ctx context.Context, data *RecipeIngredients) error
		SelectBuilder() squirrel.SelectBuilder
		FindAll(context.Context, squirrel.SelectBuilder, string) ([]*RecipeIngredients, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*RecipeIngredients, error)

		Delete(ctx context.Context, id int64) error
	}

	defaultRecipeIngredientsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RecipeIngredients struct {
		Id           int64         `db:"id"`            // 菜谱ID
		IngredientId sql.NullInt64 `db:"ingredient_id"` // 食材ID
	}
)

func newRecipeIngredientsModel(conn sqlx.SqlConn) *defaultRecipeIngredientsModel {
	return &defaultRecipeIngredientsModel{
		conn:  conn,
		table: "`recipe_ingredients`",
	}
}

func (m *defaultRecipeIngredientsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRecipeIngredientsModel) FindOne(ctx context.Context, id int64) (*RecipeIngredients, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", recipeIngredientsRows, m.table)
	var resp RecipeIngredients
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRecipeIngredientsModel) FindOneByIdIngredientId(ctx context.Context, id int64, ingredientId sql.NullInt64) (*RecipeIngredients, error) {
	var resp RecipeIngredients
	query := fmt.Sprintf("select %s from %s where `id` = ? and `ingredient_id` = ? limit 1", recipeIngredientsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, id, ingredientId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRecipeIngredientsModel) Insert(ctx context.Context, data *RecipeIngredients) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, recipeIngredientsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.IngredientId)
	return ret, err
}

func (m *defaultRecipeIngredientsModel) Update(ctx context.Context, newData *RecipeIngredients) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, recipeIngredientsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.IngredientId, newData.Id)
	return err
}

func (m *defaultRecipeIngredientsModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}

func (m *defaultRecipeIngredientsModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*RecipeIngredients, error) {

	builder = builder.Columns(recipeIngredientsRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	// query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	query, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*RecipeIngredients

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultRecipeIngredientsModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*RecipeIngredients, error) {

	builder = builder.Columns(recipeIngredientsRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	// query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	query, values, err := builder.OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*RecipeIngredients

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultRecipeIngredientsModel) tableName() string {
	return m.table
}
