// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: recipes.proto

package server

import (
	"context"

	"github.com/huangyisan/recipes-hub/app/recipes/cmd/rpc/internal/logic"
	"github.com/huangyisan/recipes-hub/app/recipes/cmd/rpc/internal/svc"
	"github.com/huangyisan/recipes-hub/app/recipes/cmd/rpc/pb"
)

type RecipeServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedRecipeServer
}

func NewRecipeServer(svcCtx *svc.ServiceContext) *RecipeServer {
	return &RecipeServer{
		svcCtx: svcCtx,
	}
}

// 菜单详情
func (s *RecipeServer) RecipeCreate(ctx context.Context, in *__.RecipeCreateReq) (*__.RecipeCreateResp, error) {
	l := logic.NewRecipeCreateLogic(ctx, s.svcCtx)
	return l.RecipeCreate(in)
}
