// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	ingredient "api/internal/handler/ingredient"
	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// ingredient list
				Method:  http.MethodPost,
				Path:    "/List",
				Handler: ingredient.IngredientListHandler(serverCtx),
			},
			{
				// ingredient detail
				Method:  http.MethodPost,
				Path:    "/detail",
				Handler: ingredient.IngredientDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/ingredient"),
	)
}
