// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	ingredient "github.com/huangyisan/recipes-hub/app/ingredients/cmd/api/internal/handler/ingredient"
	"github.com/huangyisan/recipes-hub/app/ingredients/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// ingredient all list
				Method:  http.MethodGet,
				Path:    "/all",
				Handler: ingredient.IngredientAllHandler(serverCtx),
			},
			{
				// ingredent create
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: ingredient.IngredientCreateHandler(serverCtx),
			},
			{
				// ingredient detail
				Method:  http.MethodPost,
				Path:    "/detail",
				Handler: ingredient.IngredientDetailHandler(serverCtx),
			},
			{
				// ingredient list
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: ingredient.IngredientListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/ingredient"),
	)
}
