// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type Ingredient struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	ImageContent string `json:"image_content"`
	Description  string `json:"description"`
}

type IngredientAllReq struct {
	OrderBy string `json:order_by`
}

type IngredientAllResp struct {
	List []Ingredient `json:"list"`
}

type IngredientCreateReq struct {
	Name         string `form:"name"`
	ImageContent string `form:"image_content,optional"`
	Description  string `form:"description,optional"`
}

type IngredientCreateResp struct {
	Ingredient Ingredient `json:"data"`
}

type IngredientDetailReq struct {
	Name string `json:"name"`
}

type IngredientDetailResp struct {
	Ingredient Ingredient `json:"ingredient"`
}

type IngredientListReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type IngredientListResp struct {
	List []Ingredient `json:"list"`
}
