// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type Ingredient struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	ImageUrl    string `json:"image_url"`
	Description string `json:"description"`
}

type IngredientCreateReq struct {
	Name         string `json:"name"`
	ImageContent string `json:"image_content,optional"`
	Description  string `json:"description,optional"`
}

type IngredientCreateResp struct {
}

type IngredientDetailReq struct {
	Name string `json:"name"`
}

type IngredientDetailResq struct {
	Ingredient Ingredient `json:"ingredient"`
}

type IngredientListReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type IngredientListResp struct {
	List []Ingredient `json:"list"`
}
