// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	recipe "github.com/huangyisan/recipes-hub/app/recipes/cmd/api/internal/handler/recipe"
	"github.com/huangyisan/recipes-hub/app/recipes/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// recipe recipeCreateResp
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: recipe.RecipeCreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/recipe"),
	)
}
