// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: recipes.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RecipeClient is the client API for Recipe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecipeClient interface {
	// 菜单详情
	//
	//	rpc ingredientDetail(IngredientDetailReq) returns (IngredientDetailResp);
	//
	// 食材列表
	//
	//	rpc ingredientList(IngredientListReq) returns (IngredientListResp);
	//
	// 添加菜单
	RecipeCreate(ctx context.Context, in *RecipeCreateReq, opts ...grpc.CallOption) (*RecipeCreateResp, error)
}

type recipeClient struct {
	cc grpc.ClientConnInterface
}

func NewRecipeClient(cc grpc.ClientConnInterface) RecipeClient {
	return &recipeClient{cc}
}

func (c *recipeClient) RecipeCreate(ctx context.Context, in *RecipeCreateReq, opts ...grpc.CallOption) (*RecipeCreateResp, error) {
	out := new(RecipeCreateResp)
	err := c.cc.Invoke(ctx, "/pb.recipe/recipeCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecipeServer is the server API for Recipe service.
// All implementations must embed UnimplementedRecipeServer
// for forward compatibility
type RecipeServer interface {
	// 菜单详情
	//
	//	rpc ingredientDetail(IngredientDetailReq) returns (IngredientDetailResp);
	//
	// 食材列表
	//
	//	rpc ingredientList(IngredientListReq) returns (IngredientListResp);
	//
	// 添加菜单
	RecipeCreate(context.Context, *RecipeCreateReq) (*RecipeCreateResp, error)
	mustEmbedUnimplementedRecipeServer()
}

// UnimplementedRecipeServer must be embedded to have forward compatible implementations.
type UnimplementedRecipeServer struct {
}

func (UnimplementedRecipeServer) RecipeCreate(context.Context, *RecipeCreateReq) (*RecipeCreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecipeCreate not implemented")
}
func (UnimplementedRecipeServer) mustEmbedUnimplementedRecipeServer() {}

// UnsafeRecipeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecipeServer will
// result in compilation errors.
type UnsafeRecipeServer interface {
	mustEmbedUnimplementedRecipeServer()
}

func RegisterRecipeServer(s grpc.ServiceRegistrar, srv RecipeServer) {
	s.RegisterService(&Recipe_ServiceDesc, srv)
}

func _Recipe_RecipeCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecipeCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServer).RecipeCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.recipe/recipeCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServer).RecipeCreate(ctx, req.(*RecipeCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Recipe_ServiceDesc is the grpc.ServiceDesc for Recipe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recipe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.recipe",
	HandlerType: (*RecipeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "recipeCreate",
			Handler:    _Recipe_RecipeCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recipes.proto",
}
